Un-Like Song Feature
h-le/fa-starter pull request #19
Opened 2020-10-16 23:24 UTC by h-le

- Client-Side
  - [ ] Add button/method to send `POST` request to server, with song data

- Server-Side
  - [ ] Create route to `delete()` previously liked song in `likes` collection

2020-10-20 18:51 UTC, okkays requested changes

2020-10-20 18:51 UTC, okkays commented on src/app/likes/likes.component.spec.ts
> +    /* fixture.detectChanges(); */
remove

2020-10-20 18:51 UTC, okkays commented on src/app/likes/likes.component.html
> +      style="background-size: cover;"
prefer CSS to the style attribute (unless it's computed by angular as on the line above)

2020-10-20 18:51 UTC, okkays commented on src/app/likes/likes.component.ts
> +    this.hoveredLikeId = -1;
`number|null` seems like the more canonical way to represent this in TS

2020-10-20 18:51 UTC, okkays commented on app.py
> +@app.route('/_unlike', methods=['DELETE'])
FYI - you can simplify this routing a bit; routes are unique on the combination of url/method, not just url.  Given that, you could do something like:

```
@app.route('/_like/<id>', methods=['DELETE']) # Delete a like
@app.route('/_like', methods=['POST']) # Create a new like
@app.route('/_like', methods=['GET']) # Get a list of likes
```

Typical CRUD is:
```
@app.route('/things', methods=['GET']) # Get a list of things
@app.route('/things', methods=['POST']) # Create a thing
@app.route('/things/<id>', methods=['GET']) # Get a specific thing
@app.route('/things/<id>', methods=['PATCH']) # Update a specific thing
@app.route('/things/<id>', methods=['DELETE']) # Delete a specific thing
```

2020-10-22 14:01 UTC, okkays approved these changes

2020-10-22 14:01 UTC, okkays commented on src/app/likes/likes.component.spec.ts
> +  it('x', async(() => {
it('x')

2020-10-22 14:01 UTC, okkays commented on src/app/likes/likes.component.spec.ts
> +    component.unliked$.subscribe(unliked => {
remember to check out catalyst async matchers when you get your access

2020-10-22 14:01 UTC, okkays commented on src/app/likes/likes.component.spec.ts
> +        }
```suggestion
        if (!song_artist || song_artist.length !== 3) return;
        return {
          artist: String(song_artist[2]),
          title: String(song_artist[1]),
          url: String(tile.nativeElement.getElementsByTagName('a')[0].href),
        };
```

- Use guard clauses to reduce nesting
- Use === and similar for comparison, not ==

2020-10-22 18:22 UTC, h-le commented on src/app/likes/likes.component.spec.ts
> +  it('x', async(() => {
... 😅

2020-10-22 18:26 UTC, h-le commented on src/app/likes/likes.component.spec.ts
> +    component.unliked$.subscribe(unliked => {
👍

2020-10-22 18:31 UTC, merged